# Generated by Django 5.2.1 on 2025-05-19 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_user_alter_order_assigned_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driver', verbose_name='Назначенный водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicle', verbose_name='Назначенное ТС'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cargotype', verbose_name='Вид груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client', verbose_name='Клиент (Физ. лицо)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа (UTC)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization', verbose_name='Клиент (Организация)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(verbose_name='Адрес погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_datetime',
            field=models.DateTimeField(verbose_name='Плановое время погрузки (UTC)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтвержден'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления (UTC)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driver', verbose_name='Текущий водитель'),
        ),
    ]
