# Generated by Django 4.2.24 on 2025-09-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ВезёмВсё', max_length=255, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Видео (URL)')),
                ('requisites', models.TextField(verbose_name='Реквизиты')),
                ('certificate_text', models.TextField(verbose_name='Сертификат (текст)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('text', models.TextField(verbose_name='Событие/описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='main.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'История компании (запись)',
                'verbose_name_plural': 'История компании (по годам)',
                'ordering': ['-year'],
            },
        ),
    ]
