# Generated by Django 4.2.24 on 2025-09-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_companyinfo_companyhistoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Изображение (обложка)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='Видео (файл)'),
        ),
    ]
