# Generated by Django 4.2.24 on 2025-09-14 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_companyinfo_intro_image_companyinfo_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Термин / Вопрос')),
                ('answer', models.TextField(verbose_name='Определение / Ответ')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Словарь / FAQ — запись',
                'verbose_name_plural': 'Словарь / FAQ — записи',
                'ordering': ['-added_at'],
            },
        ),
    ]
